# Configuration for MarketCraft

# Default limit for the number of shops a player can have
# Default value: 5
# Set to -1 for unlimited
shopLimit: 5

# Default limit for the number of shop signs a player can have
# Default value: 5
# Set to -1 for unlimited
signLimit: 5