name: MarketCraft
version: '${version}'
main: com.marketcraft.MarketCraft
authors: [Slimerblue22]
api-version: '1.20'
load: POSTWORLD
commands:
  marketcraftdebug:
    description: Command for controlling the debug system
    aliases: [mcd]
  marketcraft:
    description: WIP stuff
    aliases: [mc]
permissions:
  marketcraft.debug:
    description: Permission for debug commands
    default: op
  marketcraft.wip:
    description: WIP stuff
    default: op