name: MarketCraft
version: '${version}'
main: com.marketcraft.MarketCraft
authors: [Slimerblue22]
api-version: '1.20'
load: POSTWORLD
commands:
  marketcraftdebug:
    description: Command for controlling the debug system (does NOT include access to admin commands)
    aliases: [mcd]
  marketcraft:
    description: Command for controlling most of the plugins functions
    aliases: [mc]
permissions:
  marketcraft.debug:
    description: Permission for debug commands
    default: op
  marketcraft.use:
    description: Permission for most of the plugins functions
    default: op
  marketcraft.admin:
    description: Admin permission (does NOT include access to debug system)
    default: op